name: Haskell-Server-Twitter
version: 0.1.0.0
github: "DimitrisNikis/Haskell-Server-Twitter"
author: "Dmitry Nikitin"
maintainer: "ddnikitin@edu.hse.ru"
copyright: "2025 Dmitry Nikitin"

extra-source-files:
  - README.md

executables:
  Haskell-Server-Twitter-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - servant
      - servant-server
      - servant-client
      - servant-client-core
      - warp
      - text
      - bytestring
      - containers
      - aeson
      - mtl
      - time
      - acid-state
      - regex-tdfa
      - safecopy
      - wai
      - http-types
      - jwt >= 0.10.0
      - bcrypt
      - random
      - string-conversions
      - servant-auth-server
      - base64-bytestring
      - cryptohash-sha256

default-extensions:
  - OverloadedStrings
  - DataKinds
  - TypeOperators
  - DeriveGeneric
  - ScopedTypeVariables
  - FlexibleInstances
  - MultiParamTypeClasses
  - TemplateHaskell
  - TypeFamilies
  - GeneralizedNewtypeDeriving
  - DeriveAnyClass