resolver: nightly-2024-10-11

packages:
- .

extra-deps:
  - jwt-0.11.0
  - x509-1.7.7
  - x509-store-1.6.9
  - cryptostore-0.3.1.0
  - x509-validation-1.6.12

ghc-options:
  "Haskell-Server-Twitter": -Wunused-imports